// Korean labels for external (out-of-dataset) characters referenced in family
// fields. When a tier upgrade lands and a character becomes a real id, remove
// its entry here so the canonical names.ko is used instead.
// Transliteration leans Greek (Aeson → 아이손) over Latin (Aeson → 아에손)
// to match the rest of the dataset's tone.
//
// Tier 3 (Phase 8) added 115 characters — many previously-external ids were
// promoted to canonical entries and removed from this map. Newly-introduced
// external refs (e.g. aeolus_thessaly for Sisyphus's father, perses_titan
// disambiguated from Perseus's son perses) are added here.
export const EXTERNAL_NAMES_KO: Record<string, string> = {
  absyrtus: '압시르토스',
  acamas: '아카마스',
  achelous: '아켈로오스',
  acis: '아키스',
  acrisius: '아크리시오스',
  adonis: '아도니스',
  aeetes: '아이에테스',
  aegialia: '아이기알리아',
  aegina: '아이기나',
  aeolus_thessaly: '아이올로스(테살리아 왕)',
  aerope: '아에로페',
  aeson: '아이손',
  aethra: '아이트라',
  agenor: '아게노르',
  alcaeus: '알카이오스',
  aletes: '알레테스',
  alpheus: '알페이오스',
  althaea: '알타이아',
  amphion: '암피온',
  amphitryon: '암피트리온',
  anchises: '안키세스',
  androgeus: '안드로게오스',
  anticlea: '안티클레이아',
  antilochus: '안틸로코스',
  antiphantes: '안티판테스',
  arcas: '아르카스',
  argia: '아르게이아',
  arion: '아리온',
  aristaeus: '아리스타이오스',
  ascanius: '아스카니우스',
  assaracus: '아사라코스',
  asteria: '아스테리아',
  astraeus: '아스트라이오스',
  astyanax: '아스티아낙스',
  athamas: '아타마스',
  atreus: '아트레우스',
  autonoe: '아우토노에',
  balius: '발리오스',
  broteas: '브로테아스',
  briseus: '브리세우스',
  calais: '칼라이스',
  callirrhoe: '칼리로에',
  cassiopeia: '카시오페이아',
  castor: '카스토르',
  centaurus: '켄타우로스',
  cepheus: '케페우스',
  ceto: '케토',
  chalciope: '칼키오페',
  chiron: '키론',
  chloris: '클로리스',
  chryses: '크리세스',
  chrysaor: '크리사오르',
  cilix: '킬릭스',
  clymene: '클뤼메네',
  coronis: '코로니스',
  crataeis: '크라타이이스',
  cretan_bull: '크레타의 황소',
  cretheus: '크레테우스',
  creusa: '크레우사(아이네이아스의 아내)',
  creusa_glauce: '크레우사/글라우케(코린토스 공주)',
  cyclopes: '키클로페스',
  deidamia: '데이다메이아',
  deiphobus: '데이포보스',
  deipyle: '데이필레',
  demophon: '데모폰',
  despoina: '데스포이나',
  deucalion: '데우칼리온',
  deucalion_minoan: '데우칼리온(미노스의 아들)',
  dia: '디아',
  dryope: '드뤼오페',
  dymas: '디마스',
  echion: '에키온',
  eetion: '에에티온',
  electra_oceanid: '엘렉트라(오케아니스)',
  electryon: '엘렉트리온',
  enarete: '에나레테',
  endeis: '엔데이스',
  endymion: '엔디미온',
  epaphus: '에파포스',
  epione: '에피오네',
  erichthonius: '에리크토니오스',
  erigone: '에리고네',
  eupalamus: '에우팔라모스',
  europa: '에우로페',
  eurybia: '에우리비아',
  eurydice_nestor: '에우리디케(네스토르의 아내)',
  eurynome: '에우리노메',
  eurysaces: '에우리사케스',
  giants: '기간테스',
  glaucus: '글라우코스(시지프스의 아들)',
  glaucus_minos: '글라우코스(미노스의 아들)',
  haemon: '하이몬',
  hedone: '헤도네',
  hekatonkheires: '헤카톤케이레스',
  hermione: '헤르미오네',
  hesione: '헤시오네',
  hippodamia: '히포다메이아',
  hippolochus: '히폴로코스',
  hippolyta: '히폴리테',
  hippomenes: '히포메네스',
  hippotes: '히포테스',
  horae: '호라이',
  hyades: '휘아데스',
  hyllus: '휠로스',
  hypseus: '휩세우스',
  iasion: '이아시온',
  iasus: '이아소스',
  icarius: '이카리오스',
  idamante: '이다만테',
  idyia: '이뒤이아',
  ilus: '일로스',
  inachus: '이나코스',
  iphicles: '이피클레스',
  laertes: '라에르테스',
  laius: '라이오스',
  laodamas: '라오다마스',
  laodamia: '라오다미아',
  laomedon: '라오메돈',
  lavinia: '라비니아',
  ladon_river: '라돈(강의 신)',
  learchus: '레아르코스',
  leda: '레다',
  lycaon: '리카온',
  macaria: '마카리아',
  meda: '메다',
  medon: '메돈',
  medus: '메도스',
  melicertes: '멜리케르테스',
  meliae: '멜리아데스',
  menoeceus: '메노이케우스',
  menoetius: '메노이티오스',
  merope: '메로페',
  mermerus: '메르메로스',
  molossus: '몰로소스',
  morpheus: '모르페우스',
  muses: '무사이',
  neleus: '넬레우스',
  nephele: '네펠레',
  nereids: '네레이데스',
  oeagrus: '오이아그로스',
  oeneus: '오이네우스',
  oenone: '오이노네',
  oileus: '오일레우스',
  oreithyia: '오레이튀이아',
  orpheus_disputed: '오르페우스(아폴론 친자설)',
  otrera: '오트레라',
  ourea: '우레아',
  pallas_titan: '팔라스(티탄)',
  pandia: '판디아',
  pandion: '판디온',
  panacea: '파나케이아',
  parthenopaeus: '파르테노파이오스',
  pasiphae: '파시파에',
  pasithea: '파시테아',
  pelopia: '펠로피아',
  peneus: '페네이오스',
  perieres: '페리에레스',
  periboea: '페리보이아',
  perse: '페르세',
  perses: '페르세스(페르세우스의 아들)',
  perses_titan: '페르세스(티탄)',
  phaethon: '파에톤',
  pheres: '페레스',
  philonoe: '필로노에',
  phlegyas: '플레기아스',
  phoenix: '포이닉스',
  phorcys: '포르키스',
  pirithous: '페이리토오스',
  pisistratus: '페이시스트라토스',
  pitys: '피티스',
  pleiades: '플레이아데스',
  pleione: '플레이오네',
  plouto_nymph: '플루토(님프)',
  plutus: '플루토스',
  poeas: '포이아스',
  polycaste: '폴리카스테',
  polydeuces: '폴리데우케스',
  polydorus: '폴리도로스',
  pothos: '포토스',
  psyche: '프시케',
  pylades: '필라데스',
  pyrrha: '피라',
  salmoneus: '살모네우스',
  sthenelus: '스테넬로스',
  strophius: '스트로피오스',
  tecmessa: '테크메사',
  telamon: '텔라몬',
  teucer: '테우크로스',
  telegonus: '텔레고노스',
  telephassa: '텔레파사',
  thaumas: '타우마스',
  thersander: '테르산드로스',
  thestor: '테스토르',
  thrasymedes: '트라쉬메데스',
  thyestes: '튀에스테스',
  thymbraeus: '튐브라이오스',
  tisamenus: '티사메노스',
  tithonus: '티토노스',
  tros: '트로스',
  tydeus: '튀데우스',
  tyndareus: '튄다레오스',
  xanthus: '크산토스',
  zetes: '제테스',
};
